from typing import Protocol


class ICacheClient(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, ttl_seconds: int = 86400) -> None: ...

    async def delete(self, key: str) -> None: ...
